I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 106, in script
    Spooner"Well lets go to eat then"
Exception: Sayer 'Spooner' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 106, in script
    Spooner"Well lets go to eat then"
  File "C:\Users\Pcreathors\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\Pcreathors\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Pcreathors\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Spooner' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.6.25022803
Schizophrenian Dream 1.0
Sat Apr 26 10:21:14 2025
